forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

application:
    resource: "@ApplicationBundle/Resources/config/routing.yml"
    prefix:   /app


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
