forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /forum

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

application:
    resource: "@ApplicationBundle/Resources/config/routing.yml"
    prefix:   /app


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
